### ISSUE TITLE
Add `galaxy` Ansible Collection type

### ISSUE THREAD

**Issue by mddeff** [Spartek-Engineering/cattledrive#14]
```yaml
- type: galaxy
  src: <collection name>
  dest: /folder/path/to/dest
  install: <bool> #install/decompress the collection, default TRUE
  server: galaxy_server_url #default to ansible-galaxy default
```
