### ISSUE TITLE
Handle 'website scripts' better

### ISSUE THREAD

**Issue by mddeff** [Spartek-Engineering/cattledrive#23]
`curl -sfL https://get.rke2.io | sh -` is a common (albeit dangerous) pattern.

```
mirror:
  - type: wget
    src: https://get.rke2.io/
    dest: /kick/testing/rke2/install.sh
```
should produce `/kick/testing/rke2/install.sh`, not `/kick/testing/rke2/install.sh/index.html`
